# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42358decb34703fdcf41693c6799b75f33fa39c7e47f904cf05c0d6c2a2e90a0cf840912472e80bcce9bb8da7b6b2a30d0783705218d2b1ed86a7e8f67fa4fd

test:
  secret_key_base: 8699af4ef87bccd9690693eaa8710d2568092f703c5a2b3cd3771a6e3a831c2a4fae4bbb5883271f4e89c3b1e0e9180545d6fc1f55399ceed45b55bd32e02007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
